### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by gisspace** [zfile-dev/zfile#324]
read.java:61)
        at java.lang.Thread.run(Unknown Source)
java.io.FileNotFoundException: F:\wangqianluo\music\Beyond - ???.mp3 (系统找不到
指定的文件。)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at im.zhaojun.zfile.util.FileUtil.export(FileUtil.java:159)
        at im.zhaojun.zfile.util.FileUtil.export(FileUtil.java:70)
        at im.zhaojun.zfile.controller.home.LocalController.downAttachment(Local
Controller.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvok
e(InvocableHandlerMethod.java:197)

**Comment by zhaojun1998** [comment]
什么功能报错的，还有文件名本身是什么

**Comment by bcaso** [comment]
本地使用 Nginx Proxy Manager，反代后中文乱码。

网页中可以播放，但是用 potplayer 就不行。

![image](https://user-images.githubusercontent.com/32212684/180210504-36722f7b-44a9-470f-8b36-de30f5868b3f.png)

反代后，所有的音频都不能在线播放。

![image](https://user-images.githubusercontent.com/32212684/180210932-29fcae4f-de86-4b4d-a81c-002683612865.png)

![image](https://user-images.githubusercontent.com/32212684/180211129-5b4a37ca-cdb0-4227-866e-97af8bc9d40e.png)

只配置了这些，其他的没有填。没有 SSL，没有在高级选项下自定义。

不使用反代，使用 IP加端口访问的话，Potplayer 得到的地址还是中文乱码。

idm 检测到的地址是正常的，可以放到 potplayer 中播放。

![image](https://user-images.githubusercontent.com/32212684/180215573-3963595c-e107-4557-9479-21a32c22099c.png)

**Comment by zhaojun1998** [comment]
@bcaso 


这个问题已记录，会测试并解决，进度会进行反馈。

**Comment by zhaojun1998** [comment]
最新版已经解决
