### ISSUE TITLE
无法显示readme文件

### ISSUE THREAD

**Issue by LxnChan** [zfile-dev/zfile#371]
## 我的环境

![image](https://user-images.githubusercontent.com/46388610/173172268-c571e62d-3ecd-40d3-8181-82278467f885.png)

## 错误日志

<details>
    <summary>点击查看日志</summary>
    <pre>
      <code>
2022-06-11 12:16:30.080 ERROR 11027 --- [http-nio-8080-exec-10] i.z.z.exception.GlobleExceptionHandler   : 文件解析异常, 请求 url = https://lxnchan-my.sharepoint.com/personal/filebucket_lxnchan_cn/_layouts/15/download.aspx?UniqueId=e28a865d-c04f-4bc5-97ad-a2d1bc7829fb&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbHhuY2hhbi1teS5zaGFyZXBvaW50LmNvbUAwMTdiMmQ5Zi1mYTVmLTQ5YWYtYTMxOC04NTA0NDk2ZWJlNTgiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjU0OTIwOTg3IiwiZXhwIjoiMTY1NDkyNDU4NyIsImVuZHBvaW50dXJsIjoiOVd3NE11blVuclBVTUg1Wm1NV3dnMGsrMU8rRStxUThITG1wMkxCV2s2MD0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE1MiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTW1NeE5qVXlNMkV0TWpZek1DMDBOMlEwTFRoaE1HTXROekE1WVdNeE1UVTNNVGM1IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IlpUQTBOR1kwT1RjdE56TmlOeTAwTW1ObExUazROekF0WldFNU9XVm1Oek13TmpkaCIsImFwcF9kaXNwbGF5bmFtZSI6IlpGaWxlIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiMDk5Mzk4MDktYzYxNy00M2M4LWEyMjAtYTkzYzE1MTNjNWQ0IiwidGlkIjoiMDE3YjJkOWYtZmE1Zi00OWFmLWEzMTgtODUwNDQ5NmViZTU4IiwidXBuIjoiZmlsZWJ1Y2tldEBseG5jaGFuLmNuIiwicHVpZCI6IjEwMDMyMDAxRjdCOTM0QUQiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMWY3YjkzNGFkQGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjIwLjE5MC4xNDQuMTcyIn0.NUoyaEhwNS9PRmNZOEVyY3BHai9ObGRMQXVJeUJZUHR5cGphVEdZSm84Zz0&ApiVersion=2.0, 异常信息为 = I/O error on GET request for "https://lxnchan-my.sharepoint.com/personal/filebucket_lxnchan_cn/_layouts/15/download.aspx": lxnchan-my.sharepoint.com; nested exception is java.net.UnknownHostException: lxnchan-my.sharepoint.com

im.zhaojun.zfile.exception.TextParseException: 文件解析异常, 请求 url = https://lxnchan-my.sharepoint.com/personal/filebucket_lxnchan_cn/_layouts/15/download.aspx?UniqueId=e28a865d-c04f-4bc5-97ad-a2d1bc7829fb&Translate=false&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvbHhuY2hhbi1teS5zaGFyZXBvaW50LmNvbUAwMTdiMmQ5Zi1mYTVmLTQ5YWYtYTMxOC04NTA0NDk2ZWJlNTgiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNjU0OTIwOTg3IiwiZXhwIjoiMTY1NDkyNDU4NyIsImVuZHBvaW50dXJsIjoiOVd3NE11blVuclBVTUg1Wm1NV3dnMGsrMU8rRStxUThITG1wMkxCV2s2MD0iLCJlbmRwb2ludHVybExlbmd0aCI6IjE1MiIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiTW1NeE5qVXlNMkV0TWpZek1DMDBOMlEwTFRoaE1HTXROekE1WVdNeE1UVTNNVGM1IiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IlpUQTBOR1kwT1RjdE56TmlOeTAwTW1ObExUazROekF0WldFNU9XVm1Oek13TmpkaCIsImFwcF9kaXNwbGF5bmFtZSI6IlpGaWxlIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiMDk5Mzk4MDktYzYxNy00M2M4LWEyMjAtYTkzYzE1MTNjNWQ0IiwidGlkIjoiMDE3YjJkOWYtZmE1Zi00OWFmLWEzMTgtODUwNDQ5NmViZTU4IiwidXBuIjoiZmlsZWJ1Y2tldEBseG5jaGFuLmNuIiwicHVpZCI6IjEwMDMyMDAxRjdCOTM0QUQiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMWY3YjkzNGFkQGxpdmUuY29tIiwic2NwIjoiYWxsZmlsZXMud3JpdGUgYWxscHJvZmlsZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjIwLjE5MC4xNDQuMTcyIn0.NUoyaEhwNS9PRmNZOEVyY3BHai9ObGRMQXVJeUJZUHR5cGphVEdZSm84Zz0&ApiVersion=2.0, 异常信息为 = I/O error on GET request for "https://lxnchan-my.sharepoint.com/personal/filebucket_lxnchan_cn/_layouts/15/download.aspx": lxnchan-my.sharepoint.com; nested exception is java.net.UnknownHostException: lxnchan-my.sharepoint.com
	at im.zhaojun.zfile.util.HttpUtil.getTextContent(HttpUtil.java:40)
	at im.zhaojun.zfile.controller.home.FileController.lambda$list$1(FileController.java:135)
	at java.util.Optional.ifPresent(Optional.java:159)
	at im.zhaojun.zfile.controller.home.FileController.list(FileController.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at im.zhaojun.zfile.filter.CorsFilter.doFilter(CorsFilter.java:39)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at im.zhaojun.zfile.filter.NotFoundFilter.doFilter(NotFoundFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1726)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
      </code>
    </pre>
</details>

## 期望行为

正常显示Readme和文件列表

## 当前行为

实际上请求失败之后会弹出提示，提示某链接获取失败并一直转圈，通过F12捕获和后台日志得知请求失败的就是`Readme.md`文件。

该问题为概率性出现（70%），出现时多次（三次以上）刷新可解决。

**Comment by zhaojun1998** [comment]
@LxnChan 

错误信息中：java.net.UnknownHostException: lxnchan-my.sharepoint.com

表示您的 dns 服务器有问题，无法解析 lxnchan-my.sharepoint.com 这个域名对应的 IP。所以加载 readme 失败。

如果是宿主机安装的 zfile，则请查看 `/etc/resolv.conf` 文件中 dns 服务是否配置，如配置，则请验证是否能解析 `lxnchan-my.sharepoint.com` 域名。

如果是 docker 安装的，请查看容器内的 `/etc/resolv.conf` 文件进行上述排查。

**Comment by LxnChan** [comment]
@zhaojun1998 
测试了几次确实是服务器概率性不能解析该域名，改个DNS服务器就好了。
提个建议：我觉得不应该由服务端解析Readme，应该服务端给客户端一个地址然后由客户端异步请求解析，解析失败不影响列表输出。

**Comment by zhaojun1998** [comment]
下版本将不再读取文件，密码和readme文件都在后台配置，读取数据库。
