### ISSUE TITLE
E5账号开的OneDrive Business在添加到zfile后很容易过期

### ISSUE THREAD

**Issue by mhqschen** [zfile-dev/zfile#378]
应该不是zfile的问题。在绑定到其他程序的时候也遇到了一样的问题。需要重新绑定。
不知道大佬知道这个授权的过期时间在哪里改么？

**Comment by zhaojun1998** [comment]
下载链接提示授权过期还是哪里提示，错误信息是什么。

**Comment by mhqschen** [comment]
访问main页面的时候报错，具体报错什么忘记了……
进admin驱动器设置重新获取下令牌就好了。

**Comment by mhqschen** [comment]
翻了下日志，应该是这个：

2022-07-04 00:26:53.906 DEBUG 7 --- [scheduling-1] i.z.z.s.OneDriveTokenRefreshSchedule     : 尝试调用 OneDrive 自动刷新 AccessToken 定时任务
2022-07-04 00:26:53.907 ERROR 7 --- [scheduling-1] i.z.z.s.OneDriveTokenRefreshSchedule     : 刷新 OneDrive Token 失败, DriveInfo: {"autoRefreshCache":false,"defaultSwitchToImgMode":false,"enable":true,"enableCache":false,"id":1,"name":"XXXXX","searchContainEncryptedFile":false,"searchEnable":false,"searchIgnoreCase":false,"type":"ONE_DRIVE"}

im.zhaojun.zfile.exception.InvalidDriveException: 此驱动器不存在或初始化失败, 请检查后台参数配置
	at im.zhaojun.zfile.context.DriveContext.get(DriveContext.java:92)
	at im.zhaojun.zfile.schedule.OneDriveTokenRefreshSchedule.lambda$autoRefreshOneDriveToken$0(OneDriveTokenRefreshSchedule.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at im.zhaojun.zfile.schedule.OneDriveTokenRefreshSchedule.autoRefreshOneDriveToken(OneDriveTokenRefreshSchedule.java:47)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:832)

**Comment by zhaojun1998** [comment]
@mhqschen 

使用的 zfile 版本是哪个版本。用的是 onedrive 还是 SharePoint，一般多久过期。

**Comment by mhqschen** [comment]
v3.2.6，OneDrive。在别的地方识别为OneDrive Business。
从日志上看应该是5/14~6/17，一个月，然后就过期了。

**Comment by zhaojun1998** [comment]
@mhqschen 

收到，这个我会观察一段时间，有结果会来反馈

**Comment by zhaojun1998** [comment]
@mhqschen 

已发布 ZFile 4.0 版本, 会标记每次 AccessToken 和 RefreshToken 刷新时间，看看还会不会有问题

**Comment by mhqschen** [comment]
Wow, 新版看着很酷炫👍
我试试看~
