### ISSUE TITLE
bug: Docker 外部存储文件删除失败

### ISSUE THREAD

**Issue by MartinRGB** [zfile-dev/zfile#466]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：是
- 当前 ZFile 版本：4.12
- 是否尝试最新版是否已解决此问题： - 是
- 是否尝试重启 ZFile，且问题依旧存在？： 是
- 是否已尝试清空浏览器缓存，且问题依旧存在？：是
- 操作系统（如 Windows、Mac、iOS、安卓）： windows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）： chrome
- 做什么操作提示的错误？： 删除 Docker 挂载的 本地存储中的文件
- 期望行为（应该是什么样的结果）： -
- 当前行为（当前是什么样的结果）：-
```
im.zhaojun.zfile.core.exception.file.operator.StorageSourceFileOperatorException: 删除文件/文件夹失败, 文件路径: /Vw3YGLxGDLkNwUlT0K9S3K/1%3A2, 文件名: Ellipse 2.png
2022-12-06 06:50:43 zfile        |      at im.zhaojun.zfile.module.storage.aspect.FileOperatorExceptionWrapperAspect.deleteExceptionWrapper(FileOperatorExceptionWrapperAspect.java:43)
2022-12-06 06:50:43 zfile        |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-12-06 06:50:43 zfile        |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-12-06 06:50:43 zfile        |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-06 06:50:43 zfile        |      at java.lang.reflect.Method.invoke(Method.java:498)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:617)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:68)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
2022-12-06 06:50:43 zfile        |      at im.zhaojun.zfile.module.storage.service.impl.LocalServiceImpl$$EnhancerBySpringCGLIB$$a3bbd11a.deleteFile(<generated>)
2022-12-06 06:50:43 zfile        |      at im.zhaojun.zfile.module.storage.controller.file.FileOperatorController.deleteFile(FileOperatorController.java:106)
2022-12-06 06:50:43 zfile        |      at im.zhaojun.zfile.module.storage.controller.file.FileOperatorController$$FastClassBySpringCGLIB$$10ea0908.invoke(<generated>)
2022-12-06 06:50:43 zfile        |      at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
2022-12-06 06:50:43 zfile        |      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
2022-12-06 06:50:43 zfile        |      at im.zhaojun.zfile.module.storage.controller.file.FileOperatorController$$EnhancerBySpringCGLIB$$950f4595.deleteFile(<generated>)
2022-12-06 06:50:43 zfile        |      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-12-06 06:50:43 zfile        |      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-12-06 06:50:43 zfile        |      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-12-06 06:50:43 zfile        |      at java.lang.reflect.Method.invoke(Method.java:498)
2022-12-06 06:50:43 zfile        |      at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
2022-12-06 06:50:43 zfile        |      at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
2022-12-06 06:50:43 zfile        |      at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
2022-12-06 06:50:43 zfile        |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
2022-12-06 06:50:43 zfile        |      at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java
```
- 错误日志（可选）：
- 复现步骤（可选）：
- 您的额外信息（可选）：

**Comment by MartinRGB** [comment]
4.1.3 fixed the issue
