### ISSUE TITLE
Eclipse中启动Springboot工程后日志中出现BeanNotOfRequiredTypeException

### ISSUE THREAD

**Issue by skychen1900** [zfile-dev/zfile#571]
为了帮助我们更好的解决您的问题，请填写以下选项（不填写完整可能会被直接关闭 issue）：

- 是否已搜索其他 issue，没有人提过这个问题？：Yes
- 是否已查阅、搜索 [ZFile 文档](https://docs.zfile.vip)，尤其是常见问题页，仍然未解决？：Yes
- 当前 ZFile 版本：3.2.5
- 是否尝试最新版是否已解决此问题：没有尝试过
- 是否尝试重启 ZFile，且问题依旧存在？：Yes
- 是否已尝试清空浏览器缓存，且问题依旧存在？：Yes
- 操作系统（如 Windows、Mac、iOS、安卓）：WIndows
- 浏览器（如 Chrome、Firefox、Safari，X 浏览器）：Chrome、Edge
- 做什么操作提示的错误？：工程启动过程中
- 期望行为（应该是什么样的结果）：不会出来例外
- 当前行为（当前是什么样的结果）：BeanNotOfRequiredTypeException
- 错误日志（可选）：

   >  org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'localServiceImpl' is expected to be of type 'im.zhaojun.zfile.service.impl.LocalServiceImpl$$EnhancerBySpringCGLIB$$938accca' but was actually of type 'im.zhaojun.zfile.service.impl.LocalServiceImpl$$EnhancerBySpringCGLIB$$938accca_2'ptBeanInstance(AbstractBeanFactory.java:417)
   >         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1277)
   >         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1234)
   >         at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
   >         at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
   >         at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
   >         at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172)
   >         at im.zhaojun.zfile.util.SpringContextHolder.getBean(SpringContextHolder.java:43)
   >         at im.zhaojun.zfile.context.DriveContext.getBeanByDriveId(DriveContext.java:123)
   >         at im.zhaojun.zfile.context.DriveContext.init(DriveContext.java:68)
   >         at im.zhaojun.zfile.context.DriveContext.setApplicationContext(DriveContext.java:52)

- 复现步骤（可选）：
- 您的额外信息（可选）：
    -    `java -jar zfile-3.2.5.jar` 执行时不会出现同样的问题。
    -   Eclipse(4.22.0) 执行时出现该问题。
         ![image](https://github.com/zfile-dev/zfile/assets/11610793/d68754a1-3d39-4d7c-a3f1-bfdba16a5d23)

**Comment by skychen1900** [comment]
2.3版，`[DriveContext#getBeanByDriveId`](https://github.com/zfile-dev/zfile/blob/2.3/src/main/java/im/zhaojun/zfile/context/DriveContext.java) 89行中的以下实现，传入的参数修改为bean的实际class后，error解消。
```
return SpringContextHolder.getBean(value.getClass());
```

⇒

```
 Class<? extends AbstractBaseFileService > clazz = (Class<? extends AbstractBaseFileService>) ClassUtils.getUserClass(value);
 return SpringContextHolder.getBean(clazz);
```

修改前的implementation中，将CGLIB的代理class作为参数传入后，会出现以下error。

> org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'localServiceImpl' is expected to be of type 'im.zhaojun.zfile.service.impl.LocalServiceImpl$$EnhancerBySpringCGLIB$$938accca' but was actually of type 'im.zhaojun.zfile.service.impl.LocalServiceImpl$$EnhancerBySpringCGLIB$$938accca_2'ptBeanInstance(AbstractBeanFactory.java:417)
