### ISSUE TITLE
创建Docker后，关闭后无法重启/无法启动/不能正常运行

### ISSUE THREAD

**Issue by mllt992** [zfile-dev/zfile#680]
## 环境信息
- ZFile 版本：`4.1.6 Pro`
- 部署方式：`Docker`
- 操作系统/设备：`Linux`
- 浏览器/版本号：`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`

## 复现步骤
绿联NAS，Docker，部署。

只要启动过一次后，如果关闭，就无法启动，日志信息请见附加信息。
【最新版本】【重启不了】【清除缓存无效】
尝试1：直接下载docker，什么也不配置，启动，首次启动成功，关闭，再启动，无法启动
尝试2：直接下载docker，映射/root/application.properties、/root/.zfile-v4/db、/root/.zfile-v4/logs、/data/file，首次正常启动，关闭后无法启动
尝试3：给予特权模式，无法解决问题

访问场景：
docker部署后，使用natfrp进行内网穿透，绑定自己的域名，使用域名进行访问。

## 预期结果
正常启动

## 实际结果
不能启动/一直在重启/启动失败

## 额外信息
2024-06-23T03:54:31.826103710Z panic: ZFile 已获软件著作权证书，且已埋点文件识别码，非法破解必将追究法律责任.【4】
2024-06-23T03:54:31.826134273Z
2024-06-23T03:54:31.826140232Z goroutine 1 [running]:
2024-06-23T03:54:31.826144739Z main.main()
2024-06-23T03:54:31.826148966Z /tmp/build/target/xjar.go:100 +0xc89
2024-06-23T03:54:35.161480855Z 开始校验
2024-06-23T03:54:35.181655578Z panic: ZFile 已获软件著作权证书，且已埋点文件识别码，非法破解必将追究法律责任.【4】
2024-06-23T03:54:35.181694198Z
2024-06-23T03:54:35.181701593Z goroutine 1 [running]:
2024-06-23T03:54:35.181707444Z main.main()
2024-06-23T03:54:35.181713150Z /tmp/build/target/xjar.go:100 +0xc89
2024-06-23T03:54:38.386190468Z 开始校验
2024-06-23T03:54:38.406352999Z panic: ZFile 已获软件著作权证书，且已埋点文件识别码，非法破解必将追究法律责任.【4】
2024-06-23T03:54:38.406401338Z
2024-06-23T03:54:38.406409721Z goroutine 1 [running]:
2024-06-23T03:54:38.406416179Z main.main()
2024-06-23T03:54:38.406444399Z /tmp/build/target/xjar.go:100 +0xc89
2024-06-23T03:54:41.737331755Z 开始校验
2024-06-23T03:54:41.758345661Z panic: ZFile 已获软件著作权证书，且已埋点文件识别码，非法破解必将追究法律责任.【4】
2024-06-23T03:54:41.758379599Z
2024-06-23T03:54:41.758385349Z goroutine 1 [running]:
2024-06-23T03:54:41.758389760Z main.main()
2024-06-23T03:54:41.758393852Z /tmp/build/target/xjar.go:100 +0xc89
2024-06-23T03:54:44.951849364Z 开始校验
2024-06-23T03:54:44.971420448Z panic: ZFile 已获软件著作权证书，且已埋点文件识别码，非法破解必将追究法律责任.【4】
2024-06-23T03:54:44.971466320Z
2024-06-23T03:54:44.971474210Z goroutine 1 [running]:
2024-06-23T03:54:44.971479163Z main.main()
2024-06-23T03:54:44.971483385Z /tmp/build/target/xjar.go:100 +0xc89
2024-06-23T03:54:48.343190980Z 开始校验
2024-06-23T03:54:48.363641698Z panic: ZFile 已获软件著作权证书，且已埋点文件识别码，非法破解必将追究法律责任.【4】
2024-06-23T03:54:48.363681271Z
2024-06-23T03:54:48.363688659Z goroutine 1 [running]:
2024-06-23T03:54:48.363694453Z main.main()
2024-06-23T03:54:48.363699959Z /tmp/build/target/xjar.go:100 +0xc89

![image](https://github.com/zfile-dev/zfile/assets/59815753/03e545aa-bd00-4310-8a02-84e61eaa1d0a)

![image](https://github.com/zfile-dev/zfile/assets/59815753/88a7d184-f2bc-48e7-864d-03da2845dae2)

![image](https://github.com/zfile-dev/zfile/assets/59815753/6ffb18d2-3d75-4a11-b8ab-c801554d6f0d)

**Comment by zhaojun1998** [comment]
已排查，大概率是绿联 docker 的问题，无法使用绿联页面上的功能对已创建的容器修改映射路径、权限等，否则会导致无法重启成功。
